-- Additive CRM reason and prospective audit. Preserve every historical stage.
SET lock_timeout = '5s';

ALTER TABLE public.contacts
  ADD COLUMN IF NOT EXISTS motivo_perda text,
  ADD COLUMN IF NOT EXISTS motivo_perda_detalhe text,
  ADD COLUMN IF NOT EXISTS estagio_alterado_em timestamptz;
ALTER TABLE public.contacts ALTER COLUMN estagio_kanban SET DEFAULT 'captacao';
ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS contacts_motivo_perda_check;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_motivo_perda_check
  CHECK (motivo_perda IS NULL OR motivo_perda IN ('preco','indisponibilidade','sem_retorno','desistiu','outro'));
ALTER TABLE public.contacts DROP CONSTRAINT IF EXISTS contacts_motivo_perda_detalhe_check;
ALTER TABLE public.contacts ADD CONSTRAINT contacts_motivo_perda_detalhe_check
  CHECK (motivo_perda_detalhe IS NULL OR length(motivo_perda_detalhe) <= 1000);

-- IDs are retained as audit references, deliberately without cascading FKs:
-- deleting an operational record must not silently delete its event history.
CREATE TABLE IF NOT EXISTS public.contact_stage_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contact_id bigint NOT NULL,
  restaurant_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('created','stage_changed','loss_reason_updated')),
  previous_stage text,
  new_stage text,
  previous_loss_reason text,
  loss_reason text,
  previous_loss_detail text,
  loss_detail text,
  actor_operator_id uuid,
  source text NOT NULL,
  database_role text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS contact_stage_events_tenant_contact_time
  ON public.contact_stage_events (restaurant_id, contact_id, occurred_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS public.reservation_status_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id uuid NOT NULL,
  restaurant_id text NOT NULL,
  event_type text NOT NULL CHECK (event_type IN ('created','status_changed')),
  previous_status text,
  new_status text NOT NULL,
  actor_operator_id uuid,
  source text NOT NULL,
  database_role text NOT NULL,
  occurred_at timestamptz NOT NULL DEFAULT clock_timestamp()
);
CREATE INDEX IF NOT EXISTS reservation_status_events_tenant_reservation_time
  ON public.reservation_status_events (restaurant_id, reserva_id, occurred_at DESC, id DESC);

ALTER TABLE public.contact_stage_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reservation_status_events ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.contact_stage_events, public.reservation_status_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON SEQUENCE public.contact_stage_events_id_seq, public.reservation_status_events_id_seq FROM PUBLIC, anon, authenticated;

CREATE OR REPLACE FUNCTION public.validate_contact_loss_reason()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE entering_loss boolean;
BEGIN
  NEW.motivo_perda := NULLIF(btrim(NEW.motivo_perda), '');
  NEW.motivo_perda_detalhe := NULLIF(btrim(NEW.motivo_perda_detalhe), '');
  entering_loss := false;
  IF TG_OP = 'INSERT' THEN
    entering_loss := NEW.estagio_kanban IN ('perdido', 'Inativo');
    NEW.estagio_alterado_em := clock_timestamp();
  ELSE
    entering_loss := NEW.estagio_kanban IN ('perdido', 'Inativo')
      AND (NEW.estagio_kanban IS DISTINCT FROM OLD.estagio_kanban
        OR NEW.motivo_perda IS DISTINCT FROM OLD.motivo_perda
        OR NEW.motivo_perda_detalhe IS DISTINCT FROM OLD.motivo_perda_detalhe);
    IF NEW.estagio_kanban IS DISTINCT FROM OLD.estagio_kanban
       OR NEW.motivo_perda IS DISTINCT FROM OLD.motivo_perda
       OR NEW.motivo_perda_detalhe IS DISTINCT FROM OLD.motivo_perda_detalhe THEN
      NEW.estagio_alterado_em := clock_timestamp();
    END IF;
    IF OLD.estagio_kanban IN ('perdido', 'Inativo')
       AND NEW.estagio_kanban NOT IN ('perdido', 'Inativo') THEN
      NEW.motivo_perda := NULL;
      NEW.motivo_perda_detalhe := NULL;
    END IF;
  END IF;
  IF entering_loss AND NEW.motivo_perda IS NULL THEN
    RAISE EXCEPTION 'Classificação de perda exige motivo informado' USING ERRCODE='23514';
  END IF;
  IF NEW.motivo_perda='outro' AND NEW.motivo_perda_detalhe IS NULL THEN
    RAISE EXCEPTION 'Informe o detalhe para o motivo outro' USING ERRCODE='23514';
  END IF;
  IF (NEW.motivo_perda IS NOT NULL OR NEW.motivo_perda_detalhe IS NOT NULL)
     AND COALESCE(NEW.estagio_kanban, '') NOT IN ('perdido', 'Inativo') THEN
    RAISE EXCEPTION 'Motivo de perda só pode ser informado com estágio perdido' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_contact_stage()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE event_name text; old_stage text; old_reason text; old_detail text;
BEGIN
  IF TG_OP='INSERT' THEN
    event_name := 'created';
  ELSIF NEW.estagio_kanban IS DISTINCT FROM OLD.estagio_kanban THEN
    event_name := 'stage_changed';
  ELSIF NEW.motivo_perda IS DISTINCT FROM OLD.motivo_perda
        OR NEW.motivo_perda_detalhe IS DISTINCT FROM OLD.motivo_perda_detalhe THEN
    event_name := 'loss_reason_updated';
  ELSE
    RETURN NEW;
  END IF;
  IF TG_OP='UPDATE' THEN
    old_stage := OLD.estagio_kanban;
    old_reason := OLD.motivo_perda;
    old_detail := OLD.motivo_perda_detalhe;
  END IF;
  INSERT INTO public.contact_stage_events
    (contact_id, restaurant_id, event_type, previous_stage, new_stage,
     previous_loss_reason, loss_reason, previous_loss_detail, loss_detail,
     actor_operator_id, source, database_role)
  VALUES (NEW.id, NEW.restaurant_id, event_name, old_stage, NEW.estagio_kanban,
    old_reason, NEW.motivo_perda, old_detail, NEW.motivo_perda_detalhe,
    NULLIF(current_setting('serena.operator_id', true), '')::uuid,
    CASE WHEN pg_trigger_depth() > 1 THEN 'reservation_sync'
         ELSE COALESCE(NULLIF(current_setting('serena.change_source', true), ''), 'database') END,
    current_user);
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.audit_reservation_status()
RETURNS trigger LANGUAGE plpgsql SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$
DECLARE old_status text;
BEGIN
  IF TG_OP='UPDATE' THEN
    IF NEW.status IS NOT DISTINCT FROM OLD.status THEN RETURN NEW; END IF;
    old_status := OLD.status;
  END IF;
  INSERT INTO public.reservation_status_events
    (reserva_id, restaurant_id, event_type, previous_status, new_status,
     actor_operator_id, source, database_role)
  VALUES (NEW.id, NEW.restaurant_id,
    CASE WHEN TG_OP='INSERT' THEN 'created' ELSE 'status_changed' END,
    old_status, NEW.status,
    NULLIF(current_setting('serena.operator_id', true), '')::uuid,
    COALESCE(NULLIF(current_setting('serena.change_source', true), ''), 'database'), current_user);
  RETURN NEW;
END;
$$;

REVOKE ALL ON FUNCTION public.validate_contact_loss_reason(), public.audit_contact_stage(), public.audit_reservation_status() FROM PUBLIC, anon, authenticated;
DROP TRIGGER IF EXISTS contacts_validate_loss_reason ON public.contacts;
CREATE TRIGGER contacts_validate_loss_reason BEFORE INSERT OR UPDATE ON public.contacts
  FOR EACH ROW EXECUTE FUNCTION public.validate_contact_loss_reason();
DROP TRIGGER IF EXISTS contacts_audit_stage ON public.contacts;
CREATE TRIGGER contacts_audit_stage AFTER INSERT OR UPDATE ON public.contacts
  FOR EACH ROW EXECUTE FUNCTION public.audit_contact_stage();
DROP TRIGGER IF EXISTS reservas_audit_status ON public.reservas;
CREATE TRIGGER reservas_audit_status AFTER INSERT OR UPDATE ON public.reservas
  FOR EACH ROW EXECUTE FUNCTION public.audit_reservation_status();

-- Preserve callers and cron compatibility, but never infer loss from elapsed time.
CREATE OR REPLACE FUNCTION public.contacts_mark_inactive(threshold_days integer DEFAULT 180)
RETURNS integer LANGUAGE plpgsql SECURITY INVOKER
SET search_path = pg_catalog, public
AS $$ BEGIN RETURN 0; END; $$;
REVOKE ALL ON FUNCTION public.contacts_mark_inactive(integer) FROM PUBLIC, anon, authenticated;
COMMENT ON FUNCTION public.contacts_mark_inactive(integer) IS
  'Deprecated no-op. Lost opportunities require an explicit reason from an operator.';
COMMENT ON TABLE public.contact_stage_events IS
  'Prospective stage/loss-reason history only. No historical backfill. Private backend access.';
COMMENT ON TABLE public.reservation_status_events IS
  'Prospective reservation status history. Records existing transitions without changing booking logic.';
