-- Created with Supabase CLI; additive, no sends or consent backfill.
SET lock_timeout='5s';

CREATE TABLE IF NOT EXISTS public.outreach_consent_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id text NOT NULL REFERENCES public.restaurants(id),
  customer_phone text NOT NULL,
  purpose text NOT NULL DEFAULT 'whatsapp_followup' CHECK (purpose='whatsapp_followup'),
  granted boolean NOT NULL,
  source text NOT NULL CHECK (source IN ('form','whatsapp_explicit','paper','import_documented','revocation')),
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  recorded_by text NOT NULL,
  evidence text NOT NULL CHECK (length(btrim(evidence)) BETWEEN 8 AND 2000),
  CHECK (NOT granted OR source <> 'revocation')
);
CREATE INDEX IF NOT EXISTS outreach_consent_latest
  ON public.outreach_consent_events(restaurant_id,customer_phone,id DESC);

CREATE TABLE IF NOT EXISTS public.outreach_rules (
  restaurant_id text NOT NULL REFERENCES public.restaurants(id),
  stage text NOT NULL CHECK (stage IN ('nurture_d3','d1','d3','d7','d30')),
  enabled boolean NOT NULL DEFAULT false,
  content_sid text CHECK (content_sid ~ '^HX[0-9a-fA-F]{32}$'),
  messaging_service_sid text CHECK (messaging_service_sid ~ '^MG[0-9a-fA-F]{32}$'),
  template_status text NOT NULL DEFAULT 'unverified',
  template_verified_at timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by text NOT NULL,
  PRIMARY KEY (restaurant_id,stage),
  CHECK (NOT enabled OR (content_sid IS NOT NULL AND template_status='approved' AND template_verified_at IS NOT NULL))
);

CREATE TABLE IF NOT EXISTS public.outreach_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  restaurant_id text NOT NULL REFERENCES public.restaurants(id),
  object_type text NOT NULL CHECK (object_type IN ('conversation','ordem_servico')),
  object_id text NOT NULL,
  stage text NOT NULL CHECK (stage IN ('nurture_d3','d1','d3','d7','d30')),
  customer_phone text NOT NULL,
  sender_phone text NOT NULL,
  content_sid text NOT NULL,
  consent_event_id bigint NOT NULL REFERENCES public.outreach_consent_events(id),
  payload jsonb NOT NULL,
  status text NOT NULL CHECK (status IN ('dispatching','sent','failed','unknown')),
  provider_message_sid text,
  provider_status text,
  error_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  finished_at timestamptz,
  UNIQUE (restaurant_id,object_type,object_id,stage),
  CHECK (status <> 'sent' OR (provider_message_sid IS NOT NULL AND provider_message_sid ~ '^SM[0-9a-fA-F]{32}$'))
);
CREATE INDEX IF NOT EXISTS outreach_outbox_by_unit
  ON public.outreach_outbox(restaurant_id,created_at DESC);

ALTER TABLE public.outreach_consent_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outreach_rules ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outreach_outbox ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.outreach_consent_events,public.outreach_rules,public.outreach_outbox FROM anon,authenticated;
REVOKE ALL ON SEQUENCE public.outreach_consent_events_id_seq,public.outreach_outbox_id_seq FROM anon,authenticated;
COMMENT ON TABLE public.outreach_consent_events IS 'Append-only application audit of explicit consent or revocation. No inference from conversations or legacy opt_in boolean.';
COMMENT ON COLUMN public.outreach_outbox.status IS 'sent means provider accepted with SID, not confirmed delivery. dispatching/unknown require manual reconciliation; never auto-retried.';
